Traceback (most recent call last):
  File "c:/python/04_The_Path_of_Python/15_dubug/1501_try_excetion.py", line 6, in division
    ans = x / y
TypeError: unsupported operand type(s) for /: 'str' and 'str'
Traceback (most recent call last):
  File "c:/python/04_The_Path_of_Python/15_dubug/1501_try_excetion.py", line 6, in division
    ans = x / y
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "c:\python\04_The_Path_of_Python\15_dubug\1501_try_excetion.py", line 6, in division
    ans = x / y
TypeError: unsupported operand type(s) for /: 'str' and 'str'
Traceback (most recent call last):
  File "c:\python\04_The_Path_of_Python\15_dubug\1501_try_excetion.py", line 6, in division
    ans = x / y
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "c:\python\04_The_Path_of_Python\15_dubug\1501_try_excetion.py", line 6, in division
    ans = x / y
TypeError: unsupported operand type(s) for /: 'str' and 'str'
Traceback (most recent call last):
  File "c:\python\04_The_Path_of_Python\15_dubug\1501_try_excetion.py", line 6, in division
    ans = x / y
ZeroDivisionError: division by zero
